service: serverless-lucas-lopes-tcc

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-common-excludes
provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 512
  timeout: 120
  region: sa-east-1
  stage: dev

functions:
  app:
    handler: index.handler
    events:
      - http:
          method: ANY
          cors: true
          path: /
  emendas:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /emendas
          cors: true
  emendasUo:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /emendas/uo
          cors: true
  emendasAutor:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /emendas/autor
          cors: true
  universidades:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /universidades
          cors: true
  universidadesNome:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /universidades/nome
          cors: true
  universidadesSigla:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /universidades/sigla
          cors: true
  universidadesUo:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /universidades/uo
          cors: true
  parlamentares:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /parlamentares
          cors: true